cloud:
  aws:
    s3:
      bucket: zurazu-bucket1
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      instanceProfile: true
      

server:
  error:
    whitelabel:
      enabled: false
spring:
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 10MB